[package]
name = "rustfetch"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
colored = "3.0.0"
mlua = { version = "0.11.3", features = ["lua54"]}
serde = "1.0.219"
serde_json = "1.0.143"
